domain:
  url: http://localhost:8080/api/v1/url-shortener/

spring:
  datasource:
    url: jdbc:postgresql://db:5432/url-shortener
    username: postgres
    password: 9337
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
